name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

    - uses: actions/checkout@v4
    
    - uses: 'google-github-actions/auth@v3'
      name: Authenticate Google Cloud
      with:
        project_id: 'records'
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: records@quixotic-moment-473715-c2.iam.gserviceaccount.com
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag europe-north2-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/erst/records:${{ github.sha }} .

    - name: Push Docker image
      run: docker push europe-north2-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/erst/records:${{ github.sha }}
