name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag europe-north2-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/erst/records:${{ github.sha }} .

    - name: Push Docker image
      run: docker push europe-north2-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/erst/records:${{ github.sha }}
